spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/test_sports_booking
    username: root
    password: Norrmejerier4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: test
