name: CI - Build & Test

on:
  push:
    branches:
      - main  # Kör när kod pushas till main
  pull_request:
    branches:
      - main  # Kör på pull requests mot main

jobs:
  build:
    runs-on: ubuntu-latest  # Kör på en Linux-server i GitHub Actions

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Hämtar koden från din repo

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build and test
        run: mvn clean verify  # Bygger och testar projektet
